name: FTC SMS Bot 24/7

on:
  workflow_dispatch: # ম্যানুয়ালি অন/অফ করার জন্য
  schedule:
    - cron: '0 */5 * * *' # প্রতি ৫ ঘণ্টা পর পর রান হবে

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330 # সাড়ে ৫ ঘণ্টার লিমিট

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium --with-deps

    - name: Start FTC Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        MY_USER: ${{ secrets.MY_USER }}
        MY_PASS: ${{ secrets.MY_PASS }}
      run: python main.py
